<a href="https://colab.research.google.com/github/ruthika5462/python-folders/blob/main/array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
##count the number of digitts in a number
n=int(input("enter a digit"))
count=0
while(n>0):
  count=count+1
  n=n//10     ##it is a floor division
print("the number of digits in the number are:",count)


enter a digit7
the number of digits in the number are: 1


In [ ]:
##python array module
import array as myarray
##creating an array
arr=myarray.array('i',[1,2,3])
arr1=myarray.array('d',[1.0,2.1,2.4,2.5,2.6])
arr2=myarray.array('u',['a','b','c'])
##type codes
print(arr.typecode)
print(arr1.typecode)
print(arr2.typecode)
#first lloking at the array
print(arr)
print(arr1)
print(arr2)

i
d
u
array('i', [1, 2, 3])
array('d', [1.0, 2.1, 2.4, 2.5, 2.6])
array('u', 'abc')


In [ ]:
##printing length of an array
print(len(arr))
print(len(arr1))
print(len(arr2))

3
5
3


In [ ]:
for i in range (0,len(arr)):
  print(arr[i],end="")
print("\n")
for i in range(0,len(arr1)):
  print(arr1[i],end="")
for i in range(0,len(arr2)):
  print(arr2[i],end="")

123

1.02.12.42.52.6abc

In [ ]:
##acessing elems from an array using index value
x=list(range(1,100,2))
new_array = myarray.array('i',x)
##printing an array
for i in range(0,len(new_array)):
  print(new_array[i],end="")
print("/n")
##accesing the element at index "25"
print(new_array[25])

123456789101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263646566676869707172737475767778798081828384858687888990919293949596979899/n
26


SyntaxError: ignored

In [2]:
import array
a=array.array('i',[1,2,3,3,5,6])
a

array('i', [1, 2, 3, 3, 5, 6])

In [4]:
import array as arr
a=arr.array('i',[1,2,3,4,5])
a

array('i', [1, 2, 3, 4, 5])

In [ ]:
from array  import*



In [6]:
##accesing array elements
a[2]
a[-1]


5

In [7]:
##basic array operations
import array as arr
a=arr.array('d',[1.1,2.1,3.1])
len(a)

3

In [14]:
##adding elements in a arrray
import array as arr
a=arr.array('d',[1.1,2.1,3.1])
a.append(3.4)
print("array a=",a)
b=arr.array('d',[5,6,7,8])
b.extend([6,4,3,2])
print("array b=",b)
c=arr.array('d',[4,5,6,7])
c.insert(2,3)
print("arrays=",c)

array a= array('d', [1.1, 2.1, 3.1, 3.4])
array b= array('d', [5.0, 6.0, 7.0, 8.0, 6.0, 4.0, 3.0, 2.0])
arrays= array('d', [4.0, 5.0, 3.0, 6.0, 7.0])


In [15]:
##removing elements of an array
import array as arr
a=arr.array('d',[1.1,2.3,4.5,3.1,7])
print("popping last element",a.pop())
print("poppig 4 th element",a.pop(3))
a.remove(1.1)
print(a)

popping last element 7.0
poppig 4 th element 3.1
array('d', [2.3, 4.5])


In [16]:
##array concatenation
import array as arr
a=arr.array('d',[1.1,2.1,3.1,2.6,7.8])
b=arr.array('d',[3.7,8.6])
c=arr.array('d')
c=a+b
print("array c=",c)

array c= array('d', [1.1, 2.1, 3.1, 2.6, 7.8, 3.7, 8.6])


In [17]:
##slicing an array
import array as arr
a=arr.array('d',[1.1,2.3,3.1,2.3,7.4])
print(a[0:3])

array('d', [1.1, 2.3, 3.1])


In [21]:
##for loop
import array as arr
a=arr.array('d',[1.1,2,5,6,7])
print("all values")
for x in a:
  print(x)
  for x in a[0:-3]:
    print(x)

all values
1.1
1.1
2.0
2.0
1.1
2.0
5.0
1.1
2.0
6.0
1.1
2.0
7.0
1.1
2.0


In [22]:
##while loop
import array as arr
a=arr.array('d',[1.1,5,67,74,3,4])
b=0
while b<len(a):
  print(a[b])
  b=b+1

1.1
5.0
67.0
74.0
3.0
4.0


In [24]:
temp=0
while temp<a[2]:
   print(a[temp])
   temp=temp+1 

1.1
5.0
67.0
74.0
3.0
4.0


IndexError: ignored

In [25]:
tem=0
while tem<len(a):
  print(a[tem])
  tem+=1

1.1
5.0
67.0
74.0
3.0
4.0


In [30]:
from array import*
vals=array('i',[5,9,8,4,2])
print(vals.buffer_info())
vals.reverse()
print(vals)
for i in range(5):
     print(vals(i))

(140289476857232, 5)
array('i', [2, 4, 8, 9, 5])


TypeError: ignored

In [31]:
from numpy import array
arr = array([2,3,4,5])
div=arr/2
print(div)


[1.  1.5 2.  2.5]


In [36]:
from array import*
nums=array("i",[1,2,3,4,5])
for i in nums:
  print(i)
  print(nums.typecode)
  print(nums.count(1))

1
i
1
2
i
1
3
i
1
4
i
1
5
i
1


In [46]:
from numpy import*
arr1 = array([[1,2,3,6,2,9],[4,5,6,7,5,3]])
print(arr1)
print(arr1.dtype)
print(arr1.ndim)
print(arr1.shape)
print(arr1.size)
arr2 = arr1.flatten()
print(arr2)
arr3=arr2.reshape(2,2,3)
print(arr3)






[[1 2 3 6 2 9]
 [4 5 6 7 5 3]]
int64
2
(2, 6)
12
[1 2 3 6 2 9 4 5 6 7 5 3]
[[[1 2 3]
  [6 2 9]]

 [[4 5 6]
  [7 5 3]]]


In [51]:
from numpy import*
m=matrix('1 2;3 6;4 5; 6 7')
print(m)
print(diagonal(m))
print(m.max())

[[1 2]
 [3 6]
 [4 5]
 [6 7]]
[1 6]
7


In [54]:
from numpy import*
m1 = matrix('1 2 3; 6 4 5; 1 6 7')
m2 = matrix('1 2 3;6 4 5; 2 6 7')
m3=m1 * m2
print(m3)

[[19 28 34]
 [40 58 73]
 [51 68 82]]


In [55]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[10,20],[30,40]])
a+b

array([[11, 22],
       [33, 44]])

In [57]:
import numpy as np
a=np.array([[10,20],[30,40]])
b=np.array([[1,2],[3,4]])
print(a*b)
print(a.dot(b))
print(help(np.dot))

[[ 10  40]
 [ 90 160]]
[[ 70 100]
 [150 220]]
Help on function dot in module numpy:

dot(...)
    dot(a, b, out=None)
    
    Dot product of two arrays. Specifically,
    
    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).
    
    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.
    
    - If either `a` or `b` is 0-D (scalar), it is equivalent to :func:`multiply`
      and using ``numpy.multiply(a, b)`` or ``a * b`` is preferred.
    
    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.
    
    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of `b`::
    
        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
    
    Parameters
    ----------
    a : array_like
        First argument.
    b : 

SyntaxError: ignored

In [ ]:
array1 = [5,3,2,4,5,6]
n = len(array1)
for i in range(o,n):
  for j in range(i+)